global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: java
    scrape_interval: 5s
    static_configs:
      - targets:
          - host.docker.internal:8089